#!/usr/bin/env python3
"""
watsonx OnToCast Agent Setup Script

This script helps you set up the watsonx OnToCast agent by guiding you through
the configuration process and testing the connection.
"""

import os
import sys
import asyncio
from typing import Dict, Optional

def print_banner():
    """Print the setup banner."""
    print("=" * 60)
    print("🤖 watsonx OnToCast Agent Setup")
    print("=" * 60)
    print("This script will help you configure your watsonx.ai agent")
    print("for use with the Live Agent Studio platform.\n")

def get_user_input(prompt: str, default: Optional[str] = None, required: bool = True) -> str:
    """Get user input with optional default value."""
    if default:
        full_prompt = f"{prompt} [{default}]: "
    else:
        full_prompt = f"{prompt}: "
    
    while True:
        value = input(full_prompt).strip()
        
        if value:
            return value
        elif default:
            return default
        elif not required:
            return ""
        else:
            print("This field is required. Please enter a value.")

def setup_watsonx_config() -> Dict[str, str]:
    """Set up watsonx.ai configuration."""
    print("📋 watsonx.ai Configuration")
    print("-" * 30)
    
    config = {}
    
    print("\n1. First, you need to get your watsonx.ai credentials:")
    print("   • Go to https://dataplatform.cloud.ibm.com/")
    print("   • Create a project or use an existing one")
    print("   • Go to 'Manage' > 'Access (IAM)' > 'API keys' to create an API key")
    print("   • Find your project ID in the project settings\n")
    
    config["WATSONX_API_KEY"] = get_user_input("Enter your watsonx.ai API key")
    config["WATSONX_PROJECT_ID"] = get_user_input("Enter your watsonx.ai Project ID")
    config["WATSONX_URL"] = get_user_input("Enter watsonx.ai URL", "https://us-south.ml.cloud.ibm.com")
    
    print("\n2. Choose your foundation model:")
    models = [
        "meta-llama/llama-3-1-70b-instruct",
        "meta-llama/llama-3-1-8b-instruct", 
        "ibm/granite-3-8b-instruct",
        "ibm/granite-3-2b-instruct",
        "mistralai/mixtral-8x7b-instruct-v01"
    ]
    
    for i, model in enumerate(models, 1):
        print(f"   {i}. {model}")
    
    while True:
        try:
            choice = int(get_user_input("Select model (1-5)", "1"))
            if 1 <= choice <= len(models):
                config["WATSONX_MODEL"] = models[choice - 1]
                break
            else:
                print("Please enter a number between 1 and 5.")
        except ValueError:
            print("Please enter a valid number.")
    
    return config

def setup_database_config() -> Dict[str, str]:
    """Set up database configuration."""
    print("\n📋 Database Configuration")
    print("-" * 30)
    
    config = {}
    
    print("\nChoose your database option:")
    print("1. Supabase (recommended)")
    print("2. PostgreSQL")
    print("3. Skip database setup (no conversation history)")
    
    while True:
        try:
            choice = int(get_user_input("Select option (1-3)", "1"))
            if choice == 1:
                print("\n• For Supabase, go to https://supabase.com/")
                print("• Create a project")
                print("• Go to Settings > API to get your URL and service key")
                config["SUPABASE_URL"] = get_user_input("Enter Supabase URL")
                config["SUPABASE_SERVICE_KEY"] = get_user_input("Enter Supabase Service Key")
                break
            elif choice == 2:
                config["DATABASE_URL"] = get_user_input("Enter PostgreSQL connection URL", 
                                                       "postgresql://user:password@localhost:5432/dbname")
                break
            elif choice == 3:
                print("⚠️  Skipping database setup - conversation history will not be persisted")
                break
            else:
                print("Please enter 1, 2, or 3.")
        except ValueError:
            print("Please enter a valid number.")
    
    return config

def setup_auth_config() -> Dict[str, str]:
    """Set up authentication configuration."""
    print("\n📋 Authentication Configuration")
    print("-" * 30)
    
    config = {}
    
    config["API_BEARER_TOKEN"] = get_user_input("Enter API Bearer Token (for authentication)", 
                                               "your-secure-token-here")
    
    return config

def write_env_file(config: Dict[str, str]):
    """Write configuration to .env file."""
    env_content = "# watsonx OnToCast Agent Configuration\n"
    env_content += "# Generated by setup script\n\n"
    
    # Group configurations
    env_content += "# watsonx.ai Configuration\n"
    for key in ["WATSONX_URL", "WATSONX_PROJECT_ID", "WATSONX_API_KEY", "WATSONX_MODEL"]:
        if key in config:
            env_content += f"{key}={config[key]}\n"
    
    env_content += "\n# Database Configuration\n"
    for key in ["SUPABASE_URL", "SUPABASE_SERVICE_KEY", "DATABASE_URL"]:
        if key in config:
            env_content += f"{key}={config[key]}\n"
    
    env_content += "\n# Authentication\n"
    if "API_BEARER_TOKEN" in config:
        env_content += f"API_BEARER_TOKEN={config['API_BEARER_TOKEN']}\n"
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print(f"\n✅ Configuration saved to .env file")

def create_sql_setup():
    """Create SQL setup file."""
    sql_content = """-- watsonx OnToCast Agent Database Setup
-- Run this SQL script on your PostgreSQL or Supabase database

-- Enable the pgcrypto extension for UUID generation (Supabase has this by default)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Create the messages table
CREATE TABLE IF NOT EXISTS messages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    session_id TEXT NOT NULL,
    message JSONB NOT NULL
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_messages_session_id ON messages(session_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON messages(created_at);

-- Verify the table was created
SELECT 'Messages table created successfully!' as status;
"""
    
    with open("setup_database.sql", "w") as f:
        f.write(sql_content)
    
    print(f"✅ Database setup script saved to setup_database.sql")
    print("   Run this script on your database to create the required tables.")

async def test_connection(config: Dict[str, str]):
    """Test the watsonx connection."""
    print("\n🧪 Testing Connection")
    print("-" * 30)
    
    try:
        # Set environment variables temporarily
        for key, value in config.items():
            os.environ[key] = value
        
        # Import and test the agent
        from watsonx_ontocast_agent import WatsonxOnToCastAgent
        
        agent = WatsonxOnToCastAgent()
        
        print("✅ watsonx.ai connection successful!")
        print(f"📋 Model info: {agent.get_model_info()}")
        
        # Test a simple query
        print("\n🧪 Testing with a sample query...")
        response = await agent.generate_response("Hello, can you introduce yourself?")
        print(f"🤖 Response: {response[:100]}...")
        
        return True
        
    except Exception as e:
        print(f"❌ Connection test failed: {str(e)}")
        return False

def main():
    """Main setup function."""
    print_banner()
    
    # Collect all configuration
    all_config = {}
    
    # watsonx configuration
    all_config.update(setup_watsonx_config())
    
    # Database configuration
    all_config.update(setup_database_config())
    
    # Authentication configuration
    all_config.update(setup_auth_config())
    
    # Write configuration files
    print("\n📝 Writing Configuration Files")
    print("-" * 30)
    
    write_env_file(all_config)
    create_sql_setup()
    
    # Test connection
    test_choice = get_user_input("\nWould you like to test the connection? (y/n)", "y", False)
    if test_choice.lower() in ['y', 'yes']:
        try:
            success = asyncio.run(test_connection(all_config))
            if success:
                print("\n🎉 Setup completed successfully!")
                print("\nNext steps:")
                print("1. If using a database, run the setup_database.sql script")
                print("2. Install dependencies: pip install -r requirements.txt")
                print("3. Run the agent: python watsonx_ontocast_agent_endpoint.py")
            else:
                print("\n⚠️  Setup completed but connection test failed.")
                print("Please check your credentials and try again.")
        except Exception as e:
            print(f"\n❌ Could not test connection: {str(e)}")
            print("Setup files have been created. Please test manually.")
    else:
        print("\n✅ Setup completed!")
        print("Configuration files have been created.")

if __name__ == "__main__":
    main()